# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: faas_storage_agent.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='faas_storage_agent.proto',
  package='faas_storage_agent',
  syntax='proto3',
  serialized_options=b'\n\032io.grpc.fass_storage_agentB\025FaasStorageAgentProtoP\001\242\002\003RTG',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x18\x66\x61\x61s_storage_agent.proto\x12\x12\x66\x61\x61s_storage_agent\"%\n\x06ns_req\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\"-\n\x07ns_resp\x12\x10\n\x08\x65rr_code\x18\x01 \x01(\x05\x12\x10\n\x08\x65rr_info\x18\x02 \x01(\t\"5\n\x08\x64\x61ta_req\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05token\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\x0c\"K\n\tdata_resp\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x0c\x12\x10\n\x08\x65rr_code\x18\x03 \x01(\x05\x12\x10\n\x08\x65rr_info\x18\x04 \x01(\t2\xfd\x03\n\x12\x66\x61\x61s_storage_agent\x12\x44\n\tcreate_ns\x12\x1a.faas_storage_agent.ns_req\x1a\x1b.faas_storage_agent.ns_resp\x12\x44\n\tdelete_ns\x12\x1a.faas_storage_agent.ns_req\x1a\x1b.faas_storage_agent.ns_resp\x12\x45\n\nconnect_ns\x12\x1a.faas_storage_agent.ns_req\x1a\x1b.faas_storage_agent.ns_resp\x12\x42\n\x03set\x12\x1c.faas_storage_agent.data_req\x1a\x1d.faas_storage_agent.data_resp\x12\x42\n\x03get\x12\x1c.faas_storage_agent.data_req\x1a\x1d.faas_storage_agent.data_resp\x12\x45\n\x06\x64\x65lete\x12\x1c.faas_storage_agent.data_req\x1a\x1d.faas_storage_agent.data_resp\x12\x45\n\x06\x65xists\x12\x1c.faas_storage_agent.data_req\x1a\x1d.faas_storage_agent.data_respB;\n\x1aio.grpc.fass_storage_agentB\x15\x46\x61\x61sStorageAgentProtoP\x01\xa2\x02\x03RTGb\x06proto3'
)




_NS_REQ = _descriptor.Descriptor(
  name='ns_req',
  full_name='faas_storage_agent.ns_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='name', full_name='faas_storage_agent.ns_req.name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='faas_storage_agent.ns_req.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=85,
)


_NS_RESP = _descriptor.Descriptor(
  name='ns_resp',
  full_name='faas_storage_agent.ns_resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='err_code', full_name='faas_storage_agent.ns_resp.err_code', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='err_info', full_name='faas_storage_agent.ns_resp.err_info', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=132,
)


_DATA_REQ = _descriptor.Descriptor(
  name='data_req',
  full_name='faas_storage_agent.data_req',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='faas_storage_agent.data_req.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='token', full_name='faas_storage_agent.data_req.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='faas_storage_agent.data_req.value', index=2,
      number=3, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=187,
)


_DATA_RESP = _descriptor.Descriptor(
  name='data_resp',
  full_name='faas_storage_agent.data_resp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='faas_storage_agent.data_resp.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='faas_storage_agent.data_resp.value', index=1,
      number=2, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='err_code', full_name='faas_storage_agent.data_resp.err_code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='err_info', full_name='faas_storage_agent.data_resp.err_info', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=189,
  serialized_end=264,
)

DESCRIPTOR.message_types_by_name['ns_req'] = _NS_REQ
DESCRIPTOR.message_types_by_name['ns_resp'] = _NS_RESP
DESCRIPTOR.message_types_by_name['data_req'] = _DATA_REQ
DESCRIPTOR.message_types_by_name['data_resp'] = _DATA_RESP
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ns_req = _reflection.GeneratedProtocolMessageType('ns_req', (_message.Message,), {
  'DESCRIPTOR' : _NS_REQ,
  '__module__' : 'faas_storage_agent_pb2'
  # @@protoc_insertion_point(class_scope:faas_storage_agent.ns_req)
  })
_sym_db.RegisterMessage(ns_req)

ns_resp = _reflection.GeneratedProtocolMessageType('ns_resp', (_message.Message,), {
  'DESCRIPTOR' : _NS_RESP,
  '__module__' : 'faas_storage_agent_pb2'
  # @@protoc_insertion_point(class_scope:faas_storage_agent.ns_resp)
  })
_sym_db.RegisterMessage(ns_resp)

data_req = _reflection.GeneratedProtocolMessageType('data_req', (_message.Message,), {
  'DESCRIPTOR' : _DATA_REQ,
  '__module__' : 'faas_storage_agent_pb2'
  # @@protoc_insertion_point(class_scope:faas_storage_agent.data_req)
  })
_sym_db.RegisterMessage(data_req)

data_resp = _reflection.GeneratedProtocolMessageType('data_resp', (_message.Message,), {
  'DESCRIPTOR' : _DATA_RESP,
  '__module__' : 'faas_storage_agent_pb2'
  # @@protoc_insertion_point(class_scope:faas_storage_agent.data_resp)
  })
_sym_db.RegisterMessage(data_resp)


DESCRIPTOR._options = None

_FAAS_STORAGE_AGENT = _descriptor.ServiceDescriptor(
  name='faas_storage_agent',
  full_name='faas_storage_agent.faas_storage_agent',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=267,
  serialized_end=776,
  methods=[
  _descriptor.MethodDescriptor(
    name='create_ns',
    full_name='faas_storage_agent.faas_storage_agent.create_ns',
    index=0,
    containing_service=None,
    input_type=_NS_REQ,
    output_type=_NS_RESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete_ns',
    full_name='faas_storage_agent.faas_storage_agent.delete_ns',
    index=1,
    containing_service=None,
    input_type=_NS_REQ,
    output_type=_NS_RESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='connect_ns',
    full_name='faas_storage_agent.faas_storage_agent.connect_ns',
    index=2,
    containing_service=None,
    input_type=_NS_REQ,
    output_type=_NS_RESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='set',
    full_name='faas_storage_agent.faas_storage_agent.set',
    index=3,
    containing_service=None,
    input_type=_DATA_REQ,
    output_type=_DATA_RESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='get',
    full_name='faas_storage_agent.faas_storage_agent.get',
    index=4,
    containing_service=None,
    input_type=_DATA_REQ,
    output_type=_DATA_RESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='delete',
    full_name='faas_storage_agent.faas_storage_agent.delete',
    index=5,
    containing_service=None,
    input_type=_DATA_REQ,
    output_type=_DATA_RESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='exists',
    full_name='faas_storage_agent.faas_storage_agent.exists',
    index=6,
    containing_service=None,
    input_type=_DATA_REQ,
    output_type=_DATA_RESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_FAAS_STORAGE_AGENT)

DESCRIPTOR.services_by_name['faas_storage_agent'] = _FAAS_STORAGE_AGENT

# @@protoc_insertion_point(module_scope)
