name: CI

on:
  # push:
  #   branches: [ master ]
  # pull_request:
  #   branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  ci:
    runs-on: [self-hosted, linux, arm64, master]
    steps:
    - uses: actions/checkout@v2
    - name: Build agent
      run: |
        pushd ${GITHUB_WORKSPACE}/agent_server
        cargo build
        popd
            
    - name: Test agent
      run: |
        pushd ${GITHUB_WORKSPACE}/agent_server
        cargo test
        popd    
        
    - name: Login to Docker Hub
      run: sudo docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}


    - name: Build and push agent docker image
      run: |
        arch=`arch`
        image_name="whysdocker/sa-${arch}:latest"
        pushd ${GITHUB_WORKSPACE}/docker/agent/
        mv ${GITHUB_WORKSPACE}/agent_server/target/debug/agent_server ./app/
        sudo docker build -t $image_name .
        sudo docker push $image_name
        popd
      
    - name: Update agent docker image in kubernetes
      run: |
        arch=`arch`
        yaml="agent-ds-${arch}.yaml"
        pushd ${GITHUB_WORKSPACE}/yaml
        sudo kubectl delete daemonset sa-ds -n openfaas-fn
        sudo kubectl create -f $yaml
        popd